# Generated by Django 4.1 on 2022-09-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datchik',
            old_name='about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='temp',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='temp',
            name='datchik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurement.datchik'),
        ),
    ]
