# Generated by Django 4.1 on 2022-09-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_about_datchik_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='datchik_id',
            new_name='sensor',
        ),
    ]
